name: Build Standalone Windows EXE

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    container: 
      image: dockcross/windows-static-x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with static Qt
      run: |
        # Inside dockcross container - already has cross-compiler
        qmake CliX.pro
        make -j4
        
    - name: Upload Standalone EXE
      uses: actions/upload-artifact@v4
      with:
        name: CliX-Standalone-Windows
        path: release/CliX.exe
