name: Build Standalone Windows EXE

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install MXE with Qt5
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git make autoconf automake autopoint bash bison bzip2 \
            flex g++ g++-multilib gettext git gperf intltool \
            libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev \
            libssl-dev libtool-bin libxml-parser-perl lzip \
            make openssl p7zip-full patch perl python3 python3-mako \
            ruby sed unzip wget xz-utils
            
        git clone https://github.com/mxe/mxe.git
        cd mxe
        # Собираем только необходимые пакеты
        make qtbase -j4 MXE_TARGETS=x86_64-w64-mingw32.static
        
    - name: Compile with qmake
      run: |
        export PATH=$(pwd)/mxe/usr/bin:$PATH
        x86_64-w64-mingw32.static-qmake-qt5 CliX.pro
        make -j4
        
    - name: Upload Standalone EXE
      uses: actions/upload-artifact@v4
      with:
        name: CliX-Standalone-Windows
        path: release/CliX.exe
