name: Debug Repository Structure

on: [push, workflow_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List all files
      run: |
        echo "=== Все файлы в репозитории ==="
        find . -type f -name "*" | head -20
        echo "=== Файлы .pro ==="
        find . -name "*.pro" 
        echo "=== Файлы .cpp ==="
        find . -name "*.cpp"
        echo "=== Файлы .h ==="
        find . -name "*.h"
        
    - name: Upload complete structure
      uses: actions/upload-artifact@v4
      with:
        name: Repository-Structure
        path: .
