name: Build Standalone Windows EXE

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    container: 
      image: dockcross/windows-static-x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        # Установим необходимые библиотеки для статической сборки
        apt-get update
        apt-get install -y pkg-config
        
    - name: Manual Qt static compilation
      run: |
        # Прямая компиляция со статическими библиотеками Qt
        /usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-g++ \
          -std=c++11 -O2 -static \
          -I/usr/src/mxe/usr/x86_64-w64-mingw32.static/include/qt5 \
          -I/usr/src/mxe/usr/x86_64-w64-mingw32.static/include/qt5/QtWidgets \
          -I/usr/src/mxe/usr/x86_64-w64-mingw32.static/include/qt5/QtGui \
          -I/usr/src/mxe/usr/x86_64-w64-mingw32.static/include/qt5/QtCore \
          main.cpp mainwindow.cpp login.cpp registration.cpp database.cpp \
          adminwindow.cpp employeeswindow.cpp masterwindow.cpp ownerwindow.cpp \
          workwindow.cpp financewindow.cpp payrollwindow.cpp salarywindow.cpp \
          schedulewindow.cpp financeswindow.cpp loginwindow.cpp \
          -o CliX.exe \
          -L/usr/src/mxe/usr/x86_64-w64-mingw32.static/lib \
          -lqtmain -lQt5Widgets -lQt5Gui -lQt5Core -lstdc++ -lgcc -lpthread
        
    - name: Upload Standalone EXE
      uses: actions/upload-artifact@v4
      with:
        name: CliX-Standalone-Windows
        path: CliX.exe
